### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ChiaraMC** [wjmaddox/drbayes#3]
Hello!

I was trying to run the visualisation jupyter notebook and had a couple of issues (I installed the repo as a package as mentioned):

- In setup.py one of the requirements is `scikit_learn>=0.20.2`. However , currently version 0.24 gets installed which actually throws some errors (I think some things have been refactored in the newest versions). I had to downgrade to 0.20.2 to get it to work, so I believe this should be changed to `scikit_learn==0.20.2` (I actually just noticed that this is specified correctly in requirements.txt, just not in setup.py)
- It would maybe be helpful if the correct Python version needed was specified? setup.py says "3.6" but 3.6.0 and 3.6.1 don't actually work (sorry I can't remember exactly now what the issues were, but I ended up using 3.6.9 to get it to work)
- Additionally, things that I had to install manually, which were not included in setup.py: seaborn and pyro-ppl

And one more thing, in the curve subspaces section of the notebook it says "Note that for this to work you need to add the repo https://github.com/timgaripov/dnn-mode-connectivity to your Python path". However, I think the version of the curves.py file in that repo might not be the same as that used in the notebook. In fact, the notebook calls
```python
model = curves.CurveNet(curve, architecture, 3, fix_end=True, fix_start=True, 
                        architecture_kwargs=model_cfg.kwargs)
```
but in the original repo that function is written as:
```python
class CurveNet(Module):
    def __init__(self, num_classes, curve, architecture, num_bends, fix_start=True, fix_end=True,
                 architecture_kwargs={}):
```
so I believe the `num_classes` argument is missing in the function call in the notebook.

Thanks!

**Comment by izmailovpavel** [comment]
Hi @ChiaraCampagnola, thank you for posting and sorry about the issues! We will update the requirements and setup file shortly. It is surprising that you had to update Python, I would expect the repo to work with `3.6.0`.
