### ISSUE TITLE
Two differend SVD implementations used in subscpaces.py

### ISSUE THREAD

**Issue by mchuck** [wjmaddox/drbayes#4]
Hi,

In `subspaces.py` you use two different SVD algorithms: `TruncatedSVD` which seems to be unused and then later `randomized_svd`. Which one is the correct one?

https://github.com/wjmaddox/drbayes/blob/0efbd081b7ccecdb2fea8e949ad81065c26faa54/subspace_inference/posteriors/subspaces.py#L129

Regards,
Maciej

**Comment by wjmaddox** [comment]
Sorry for the really long reply on this but we use the randomized SVD one -- I believe the truncated SVD itself calls a randomized SVD on the backend though.
